.PHONY: docker-build
docker-build:
	docker build -t us-central1-docker.pkg.dev/ponderada/cloud-functions-repository/consumer:latest .

.PHONY: docker-push
docker-push:
	docker push us-central1-docker.pkg.dev/ponderada/cloud-functions-repository/consumer:latest